name: icebreaker_flutter
description: Icebreaker app - Meet nearby and start conversations
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Map
  google_maps_flutter: ^2.3.0

  # State management
  provider: ^6.0.5

  # External directions
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # App icon generator
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png

flutter_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
